# -*- coding: utf-8 -*-
"""Sprint 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XC49D6Ub5D6A87LN63s1UbihBNYpvdaZ
"""

import numpy as np
import numpy
numpy.__version__

import pandas as pd
pd.read_csv('/content/food.csv')

import pandas as pd
pd.read_csv('/content/nutrition_distriution.csv')

pip install tk

from tkinter import *
import tkinter as tk

from PIL import ImageFilter,Image

import numpy as np
 
from collections import defaultdict
from sklearn.cluster import KMeans

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

import pickle
import numpy as np
from keras.models import load_model
model = load_model('model.h5')
import json
import random
intents = json.loads(open('intents2.json').read())
words = pickle.load(open('words.pkl','rb'))
labels = pickle.load(open('labels.pkl','rb'))

data=pd.read_csv('food.csv')
Breakfastdata=data['Breakfast']
BreakfastdataNumpy=Breakfastdata.to_numpy()

Lunchdata=data['Lunch']
LunchdataNumpy=Lunchdata.to_numpy()

Dinnerdata=data['Dinner']
DinnerdataNumpy=Dinnerdata.to_numpy()
Food_itemsdata=data['Food_items']

def show_entry_fields():
 print("\n Age: %s\n Veg-NonVeg: %s\n Weight: %s kg\n Hight: %s cm\n"(e1.get(),e2.get(),e3.get(),e4.get()))
def Weight_Loss():
  show_entry_fields()
breakfastfoodseparated=[]
Lunchfoodseparated=[]
Dinnerfoodseparated=[]
breakfastfoodseparatedID=[]
LunchfoodseparatedID=[]
DinnerfoodseparatedID=[]
for i in range(len(Breakfastdata)):
  if BreakfastdataNumpy[i]==1:
    breakfastfoodseparated.append( Food_itemsdata[i] )
    breakfastfoodseparatedID.append(i)
  if LunchdataNumpy[i]==1:
    Lunchfoodseparated.append(Food_itemsdata[i])
    LunchfoodseparatedID.append(i)
  if DinnerdataNumpy[i]==1:
    Dinnerfoodseparated.append(Food_itemsdata[i])
    DinnerfoodseparatedID.append(i)

LunchfoodseparatedIDdata = data.iloc[LunchfoodseparatedID]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
Valapnd=[0]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
#print(LunchfoodseparatedIDdata)

# retrieving Breafast data rows by loc method
breakfastfoodseparatedIDdata = data.iloc[breakfastfoodseparatedID]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.iloc[Valapnd]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T



